[install]
# Don't save dependencies since this is a workspace package
no_save = true

[loader]
# Treat .scm files as text for tree-sitter queries
".scm" = "text"

[define]
# Define a global for the project root to help with path resolution
"process.env.PROJECT_ROOT" = "`${process.cwd()}/../`"

[debug]
# Show more information about module resolution
show_resolution_errors = true
