version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  api:
    build: .
    command: ["uvicorn", "backend.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes: [".:/app"]
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on: [redis]
    ports: ["8000:8000"]

  worker:
    build: .
    command: ["python", "-m", "backend.worker.parallel_worker"]
    volumes: [".:/app"]
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on: [redis]